## 16. List Comprehensions

### 1. What is List Comprehensions?

---
`List comprhension` is a short and powerful way to create lists in Python using a single line of code.

Instead of writing long loops to create a list, we can write the same logic in a cleaner and faster format.

List comprhensions is compact syntax used to:

* generate a list
* transform data
* fitler element
* combine loops and condition

### 2. Why List comprehension is Used??

Benefits:

* Less code
* More readable(When use Properly)
* Faster than traditional loops
* Used heavily in real-world python programming Like: AI/ML/Deep Learning
* Best for data transformation and filtering.

### 3. Traditional Approach VS List comprehensions

##### Example: Create a list of Square from range 1 ,20

In [3]:
list1 = []
for i in range(1,21):
    sqr = i**2
    # print(sqr)
    list1.append(sqr)
print("List of Square values is:",list1)

List of Square values is: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]

In [ ]:
# [expression, for item in range()]

In [5]:
[i**2 for i in range(1,11)]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [7]:
### Dictinary comprehension

{a:a**2 for a in range(1,11)}

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

In [10]:
# lambda function 

list1 = [1,2,3,4,5,6,7,8,9,10]

tuple(map(lambda a:a**2,list1))

(1, 4, 9, 16, 25, 36, 49, 64, 81, 100)

In [ ]:
list
dictionary
set

In [ ]:
string
tuple

### 4. General Syntax of List Comprehensions

[expression for item in iterable]


Breakdown:

----

|Part|Meaning|
|----|----|
|expresion|What you want to store in the list|
|item| Variables that takes values|
|iterable| List, tuple, set, dictionary, string, etc.|

### 5.List Comprehension with conditions(Filtering)

In [11]:
[i for i in range(1,11)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [12]:
### Even Number

# Traditional Method

In [14]:
# Traditional method
list1 = []
for i in range(1,11):
    if i%2==0:
        # print(i)
        list1.append(i)
print(list1)

[2, 4, 6, 8, 10]

In [17]:
# lambda with filter
list1 = [1,2,3,4,5,6,7,8,9,10]
tuple(filter(lambda a:a%2==0,list1))

(2, 4, 6, 8, 10)

## list comprehension
##### [expression for item in iterable if condition]

In [21]:
[i for i in range(1,11) if i%2==0]

[2, 4, 6, 8, 10]

In [20]:
2%2==0

True

In [ ]:
### Example: Replace odd number with 0

In [22]:
[2, 4, 6, 8, 10]

[2, 4, 6, 8, 10]

In [23]:
[a for a in range(1,11)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [24]:
# 01 - 1

# [expression_if_true if condition else expression_if_false for item in iterable]

In [25]:
[i if i%2==0 else 0 for i in range(1,11)]

[0, 2, 0, 4, 0, 6, 0, 8, 0, 10]

In [ ]:
# 0101010 ==

In [ ]:
# [expression for i in iterable if condition]

In [28]:
[i for i in range(1,11) if i%2==0 else 0]

SyntaxError: invalid syntax (1335240581.py, line 1)

In [34]:
[i if i%2==0 else 0 for i in range(1,11)]

[0, 2, 0, 4, 0, 6, 0, 8, 0, 10]

### Nested List Comprehension

Syntax:

[expression for item1 in iterable for item2 in iterable2]

## Generate Pairs

In [35]:
[(x,y) for x in [1,2,3] for y in [10,20]]

[(1, 10), (1, 20), (2, 10), (2, 20), (3, 10), (3, 20)]

In [ ]:
[(1,10),(1,20),(2,10),(2,20),(3,10),(3,20)]

In [38]:
list1 = []
for x in [1,2,3]:
    # print(x)
    for y in [10,20]:
        # print(x,y)
        list1.append((x,y))
print(list1)

[(1, 10), (1, 20), (2, 10), (2, 20), (3, 10), (3, 20)]

*
**
***
****

In [40]:
for i in range(1,5):
    print("*"*i)

*
**
***
****

In [41]:
["*"*i for i in range(1,5)]

['*', '**', '***', '****']

### 10. List Comprehension with Strings

Example: Extract Vowels

In [45]:
vowList = []
x = "Python is programming Language A"

for i in x:
    if i in "aeiouAEIOU":
        # print(i)
        vowList.append(i)
print(vowList)

['o', 'i', 'o', 'a', 'i', 'a', 'u', 'a', 'e', 'A']

In [47]:
x = "Python is programming Language A"
[ch for ch in x if ch in "aeiouAEIOU"]

['o', 'i', 'o', 'a', 'i', 'a', 'u', 'a', 'e', 'A']

#### 11. List Comprehension with Functions

Example: Apply len() on list of words

In [49]:
words = ["python","java","c","javascript"]
wordsCount = []
for i in words:
    count = 0
    for j in i:
        count+=1
    wordsCount.append(count)
    print(i)
print(wordsCount)

python
java
c
javascript
[6, 4, 1, 10]

In [50]:
words = ["python","java","c","javascript"]
[len(word) for word in words]

[6, 4, 1, 10]

In [52]:
### 12. List Comprehension with strip() and cleaning data

In [53]:
names = ["      Mohammad   ","   Maria      ","Ajay     ", "     Rudra","Yash    ","Vaishnavi      "]
print(names)

[name.strip()  for name in names]

['      Mohammad   ', '   Maria      ', 'Ajay     ', '     Rudra', 'Yash    ', 'Vaishnavi      ']

['Mohammad', 'Maria', 'Ajay', 'Rudra', 'Yash', 'Vaishnavi']

In [56]:
names = ["      Mohammad   ","   Maria      ","Ajay     ", "     Rudra","Yash    ","Vaishnavi      "]
print(names)


list1 = []
for i in names:
    cleanNames = i.strip()
    # print(i)
    list1.append(cleanNames)
print(list1)

['      Mohammad   ', '   Maria      ', 'Ajay     ', '     Rudra', 'Yash    ', 'Vaishnavi      ']
['Mohammad', 'Maria', 'Ajay', 'Rudra', 'Yash', 'Vaishnavi']

## 13. List Comprhension with Split()

In [1]:
# Test Topics
# ------------
# 1). OOPs
# 2). FileHandling
# 3). Lambda
# 4). List Comprehension
## --> 18-06-2026
# ----------------------------------

### 13. List Comprehension with split()

In [2]:
sentence="Python is very easy"
print(sentence)
print(type(sentence))

Python is very easy
<class 'str'>

In [7]:
list1 = []
for i in sentence.split():
    # print(text)
    print(i)
# print(list1)

Python
is
very
easy

In [8]:
[word for word in sentence.split()]

['Python', 'is', 'very', 'easy']

### 14. List Comprehension with Type Data
Convert list of strings to integers

In [15]:
nums = ["10","20","30"]
# print(type(nums[0]))
for i in nums:
    num = int(i)
    print(num)
    print(type(num))

10
<class 'int'>
20
<class 'int'>
30
<class 'int'>

In [16]:
nums = ["10","20","30"]
[int(n) for n in nums]

[10, 20, 30]

### 15. List Comprehension with Dictionary

Example:

In [17]:
data = {"name":"John","age":25,"city":"Texas"}

# Extract key

for key in data:
    print(key)

name
age
city

In [18]:
for key in data.keys():
    print(key)

name
age
city

In [19]:
for value in data.values():
    print(value)

John
25
Texas

In [21]:
for i,j in data.items():
    print(i,":",j)

name : John
age : 25
city : Texas

In [22]:
data = {"name":"John","age":25,"city":"Texas"}


[key for key in data]

['name', 'age', 'city']

In [23]:
[value for value in data.values()]

['John', 25, 'Texas']

In [28]:
[(i,j) for i,j in data.items()]

[('name', 'John'), ('age', 25), ('city', 'Texas')]

#### 16. List Comprehension with enumerate()

Example: Get index and value

In [29]:
items = ['apple',"banana","mango"]

for i in items:
    print(i)

apple
banana
mango

In [33]:
items = ['apple',"banana","mango"]
for i in range(len(items)):
    print(i,items[i])

0 apple
1 banana
2 mango

In [34]:
items = ['apple',"banana","mango"]
[(i,j) for i,j in enumerate(items)]

[(0, 'apple'), (1, 'banana'), (2, 'mango')]

In [ ]:
#### 17.

In [38]:
items = ['apple',"banana","mango"]
len(items)
for i in range(len(items)):
    print(i,items[i])

0 apple
1 banana
2 mango

In [36]:
range(3)

range(0, 3)

In [37]:
for i in range(3):
    print(i)

0
1
2

### 17. List Comprehension with zip()

In [39]:
names = ["Maria","Vaishnavi","Ajay","Rudra","Yash"]
scores = [90,45,66,94,99]

print(names)
print(scores)

['Maria', 'Vaishnavi', 'Ajay', 'Rudra', 'Yash']
[90, 45, 66, 94, 99]

In [42]:
for n,s in zip(names,scores):
    print((n,s))

('Maria', 90)
('Vaishnavi', 45)
('Ajay', 66)
('Rudra', 94)
('Yash', 99)

In [43]:
names = ["Maria","Vaishnavi","Ajay","Rudra","Yash"]
scores = [90,45,66,94,99]
[(n,s) for n,s in zip(names,scores)]

[('Maria', 90), ('Vaishnavi', 45), ('Ajay', 66), ('Rudra', 94), ('Yash', 99)]

### 18. List Comprehension with Flattening List

Example :

In [44]:
list1 = [10,20,30,40,50,50]  # series -1-D
print(list1)
print(type(list1))

[10, 20, 30, 40, 50, 50]
<class 'list'>

In [48]:
import pandas as pd

In [49]:
df = pd.DataFrame(list1)
df

    0
0  10
1  20
2  30
3  40
4  50
5  50

### 2-D Data

In [51]:
matrix = [[1,2],[3,4],[5,6]]
print(matrix)
print(type(matrix))

[[1, 2], [3, 4], [5, 6]]
<class 'list'>

In [52]:
df2 = pd.DataFrame(matrix)
df2

   0  1
0  1  2
1  3  4
2  5  6

### 2-D into Series

In [59]:
matrix = [[1,2],[3,4],[5,6]]

for row in matrix:
    # print(i)
    for num in row:
        print(num)

1
2
3
4
5
6

In [60]:
matrix = [[1,2],[3,4],[5,6]]
[num for row in matrix for num in row]

[1, 2, 3, 4, 5, 6]

#### 19. Using List Comprehension with Logical Conditions

In [61]:
marks = [34,56,78,90,45]

# filter numbers greater than 50
print(marks)

[34, 56, 78, 90, 45]

In [64]:
list1 = []
for num in marks:
    # print(num)
    if num>50:
        # print(num)
        list1.append(num)
print(list1)

[56, 78, 90]

In [66]:
marks = [34,56,78,90,45]


[num for num in marks if num>50]

[56, 78, 90]

### 20. List Comprehension with Multiple Conditions

Example Filter even number divisible by 3

In [68]:
for i in range(1,10):
    if i%2==0 and i%3==0:
        print(i)

6

In [69]:
[i for i in range(1,11) if i%2==0 and i%3==0]

[6]

### 21. Using not Condition

##### Example: Remove empty strings

In [71]:
data = ["Python","","Java","","C"]

for i in data:
    # print(i)
    if i == "":
        continue
    print(i)

Python
Java
C

In [73]:
data = ["Python","","Java","","C"]
[x for x in data if x]

['Python', 'Java', 'C']

In [ ]:
# Generator or Decorator